### ISSUE TITLE
Which channel do personal notifications go to?

### ISSUE THREAD

**Issue by poohsen** [alexkvak/teamcity-slack#110]
Notifications for build configurations work for us. But not the personal notifications: 
https://build.thenewmotion.com/profile.html?notificatorType=Slack&item=userNotifications

I assume that tab is provided by this plugin. My apologies if this is not the case.
But if it is: where can I set the channel that the personal slack notification is supposed to go to?
I'm running TeamCity Enterprise 2019.2.2 (build 71923)

**Comment by alexkvak** [comment]
Yes, this is not the case. 

This plugin settings are available at https://<your-domain>/buildConfiguration/MyAwesomeProject?buildTypeTab=Slack

![изображение](https://user-images.githubusercontent.com/1052418/86268255-9411af00-bbd0-11ea-89ed-dd1a7bbb7800.png)

**Comment by poohsen** [comment]
sorry and thanks for the answer!
