### ISSUE TITLE
Plugin loads full build history causing memory issues in teamcity

### ISSUE THREAD

**Issue by nklprkh6** [alexkvak/teamcity-slack#111]
This slack-plugin seems loading the full build history. Given the size of our installation, this build history is becomes pretty large, and that's what makes the threads take over 40 minutes to process and load so much information into memory, leading to the memory outage on teamcity server. As per JetBrains support, the issue seems to be following line:

https://github.com/alexkvak/teamcity-slack/blob/master/slackIntegration-server/src/main/scala/com/fpd/teamcity/slack/controllers/BuildSettingsTry.scala#L68

**Comment by alexkvak** [comment]
@nklprkh6 thanks for detailed report!

Could you try with the new plugin version?
