### ISSUE TITLE
Show only commit title instead of body in changes placeholder

### ISSUE THREAD

**Issue by Bullrich** [alexkvak/teamcity-slack#113]
Is there a way to show only the commit titles instead of the full body of each commit in a build?

We add a lot of information in the body about the change, but all of this isn't necessary in the slack message.

This is my current format:
<pre>
<{link}|{branch} - {number}>
Status: {status}
---
{changes}
</pre>

Right now we have something like:
```
feat/abcd - 30
Status: Succeeded
---
Fixed bug a

I fixed the bug a by taking the approach of B and modifying C to fix the nuclear sinergy that atom division takes when making a sushi sandwich.
Time 32 days
Added feature JK

I ate a pizza with salad and had the idea to reset everything and remove this component and use a library instead because I didn't wanted to reinvent the wheel
Time 6 years
Removed localization in Klingon

The PO found it and didn't thought that it was funny so we removed it.
mIw'a' 'oH chenmoHlu'pu'
Time 25 minutes
```

When I would actually prefer to have something like
```
feat/abcd - 30
Status: Succeeded
---
Fixed bug a
Added feature JK
Removed localization in Klingon
```

I have been looking but I didn't find any way or option to do that.

Thanks!

**Comment by Bullrich** [comment]
Thanks for fixing it!

**Comment by alexkvak** [comment]
Support this plugin with the star ⭐️ 🙂
