### ISSUE TITLE
slack option in project not found

### ISSUE THREAD

**Issue by Fabricio872** [alexkvak/teamcity-slack#116]
hello 
I have installed new app in slack and copied oauth access token as described in documentation but the option in project is not shown in both classic and experimental view.

I have latest plugin version which is now 1.8.1
and latest TeamCity version on docker 2020.1.5 (build 78938)

also i am not very sure what to put in Public artifacts URL

maybe i am only missing something can anybody help?

**Comment by alexkvak** [comment]
Feel free to reopen if needed
