### ISSUE TITLE
Can't use private Slack channels

### ISSUE THREAD

**Issue by tallior** [alexkvak/teamcity-slack#117]
When trying to use a private Slack channel, getting this error:
Unable to find channel with name xxxxxxx

It would be great if we could post messages to private channels.

**Comment by alexkvak** [comment]
You should add your TeamCity application to your private channel

**Comment by tallior** [comment]
still doesn't work. ..

**Comment by alexkvak** [comment]
Do you remove heading `#` from channel name?

**Comment by tallior** [comment]
yes, tried both with and without it

**Comment by alexkvak** [comment]
Could you read teamcity-server.log? Is there any details?

**Comment by alexkvak** [comment]
Could you try new 2.0.0 pre-release?
