### ISSUE TITLE
Invalid Auth

### ISSUE THREAD

**Issue by Deams51** [alexkvak/teamcity-slack#119]
Just started to set up a new TeamCity server.
I've followed the setup in the Readme (creating a classic app...).
But when trying to set it up on Teamcity, I am getting an `invalid_auth` error. 

Same error when trying `https://slack.com/api/rtm.start?token=xoxp-my-long-token-here`

Version: 1.8.1

**Comment by Black-Stork** [comment]
Yeah, having the same issue

**Comment by constantnoise** [comment]
I am also having the same issue. Trying to connect an existing TeamCity to a new copy of the app.

**Comment by alexkvak** [comment]
It seems that Slack has deprecated some APIs

https://api.slack.com/changelog
https://github.com/Itiviti/simple-slack-api/issues/279

**Comment by alexkvak** [comment]
@constantnoise @Black-Stork @Deams51 I've replaced Itiviti/simple-slack-api with official library from Slack team and need some time to test the plugin. Basic functionality works fine. Even new bot apps, not only classic.

If you interested in testing I can publish beta version and you can use it.

**Comment by constantnoise** [comment]
That would be great, thanks!

**Comment by nikolaigauss** [comment]
I wouldn't mind re-configuring the Slack integration with the APIs on my test platform as well, do please include me on the beta if this means a meaningful test :).

**Comment by alexkvak** [comment]
@nikolaigauss @constantnoise I’ve just published beta.1 version https://github.com/alexkvak/teamcity-slack/releases/tag/v2.0.0-beta.1

I tested simple positive cases – the plugin posts notifications to the channels, stores the configuration in Administration section.

I have doubts if the proxy works. And if there is an error on configuration page – it does not shown.

Take a look at not permission list in readme https://github.com/alexkvak/teamcity-slack/blob/release/2.0.0/README.md

**Comment by constantnoise** [comment]
I've tested this now. It appears to work. Pasting in the OAuth access token, and hitting Submit resulted in no errors. I have only tested using the "Try it" button, and it sends to the correct channel. Will verify with daily and continuous build notifications. Thanks!

**Comment by constantnoise** [comment]
In further testing, notifications only work when I manually press "Try It" from the build, Slack menu. Notifications are not triggering automatically. Everything appears to be setup correctly. The per build settings haven't changed since before. Also, unsure if it's related, when I do click on the Build, Slack menu, the loading icon and text appear, and don't disappear. 
![image](https://user-images.githubusercontent.com/14359333/110953907-c8349680-833f-11eb-875d-9ec3cd318f5c.png)

**Comment by alexkvak** [comment]
Just checked your case, it works fine. I see `Started` and `Succeeded` status.

Could you check teamcity-server.log (`/admin/admin.html?item=diagnostics&tab=logs&file=teamcity-server.log`)

**Comment by constantnoise** [comment]
Thanks alexkvak! False alarm. I'm new to TC and Slack, In my haste I hadn't installed the app to the workspace!

**Comment by alexkvak** [comment]
Just published beta.3 version. In previous versions private messages should not work.

**Comment by alexkvak** [comment]
2.0.0 stable release, this issue can be closed. Thanks for help!
