### ISSUE TITLE
Unable to set up correct branch

### ISSUE THREAD

**Issue by johhorn** [alexkvak/teamcity-slack#12]
I have set up this plugin in teamcity, and it should post to slack when the build succeeds or fails. If I click the "Try it" link, it posts a message to the correct channel with the correct status, name and build number. The branch is set as unknown:

```
----------------
MyProject :: master - 79
Branch: Unknown
Status: succeeded
```

But when the build actually succeeds or fails, nothing happens in slack. 

I have the following settings:

Branch: master
Slack channel: techfeed
And/or notify commiters: [x]
Message template: the default template
Trigger when build is successful: [x]
Trigger when build is failed: [x]

What am I supposed to put in the branch-field? I only want to trigger slack notifications for the master branch.

**Comment by alexkvak** [comment]
Does TeamCity detect your branch name?

**Comment by johhorn** [comment]
Good question! I'm not sure, how can I check that it does? Or rather, what settings do I have to add to make sure it detects the name?

**Comment by johhorn** [comment]
I added branch specification to the VCS root, and get the following in slack when clicking "Try it" now. It still does not post when the build fails/starts/succeed, however

```
Branch: master
Status: failed
```

**Comment by alexkvak** [comment]
Ok, now let’s check server log. Please google teamcity server log

**Comment by johhorn** [comment]
Sorry, it actually does post when the build fails and succeeds now! My bad. It doesn't post when the build starts, but I can live with that :) I'll close the issue - thank you for all the help debugging!

**Comment by alexkvak** [comment]
Make sure you have the latest version, you should have separate checkbox for started builds notifications.

**Comment by johhorn** [comment]
I had the latest version, downloaded today. I also checked the separate checkbox, but it posted nothing when the build started.
