### ISSUE TITLE
weird Unable to find slack channel issue after upgrading 1.8.1 > 2.0.2

### ISSUE THREAD

**Issue by YoungjaeKim** [alexkvak/teamcity-slack#123]
Hi. always thanks for your amazing job.

Note that I've already checked #121 and #122

1. It can send Slack messages in 1.8.1 era build setups, which means Slack token is valid and the plugin seems to work.
2. There's no failure or notable log message in TeamCity server log.
3. I cannot downgrade plugin because TeamCity does not allow to downgrade it. (I'm worried delete Slack Integration because I already have lots of settings)
4. Of course the bot is invited to channels. I've heavily used the plugin since v1.4.0
5. 1 day passed since I upgraded the plugin. reboot many times.

For above reasons, I cannot create new Slack message to a build. hmm...

It just shows 'Unable to find channel with name ***' The channel name I've entered is just whatever well-sent channels now.

What can I check more?

TeamCity: v2020.2.3 (build 86002)
Slack types: Slack Enterprise, both private/public channel tested.

**Comment by YoungjaeKim** [comment]
I uploaded v1.8.1 zip to Diagnostics > Browse Data directory, and checked it works fine. I can add a new Slack message now. There seems something in `isChannelExists` logic.

**Comment by alexkvak** [comment]
Sorry for delay, you can download `slackIntegration.json` from `~/TeamCity/data/config/slackIntegration.json`, remove plugin and install the new version. Then override this file and restart TeamCity once again

**Comment by alexkvak** [comment]
Did you try `Try it` feature?

**Comment by alexkvak** [comment]
Probably you have the same issue as #129

Could you try v2.1.3 release?

**Comment by YoungjaeKim** [comment]
@alexkvak Thanks. Let me try 2.1.3 today, and will circle back to you.

**Comment by YoungjaeKim** [comment]
@alexkvak Confirmed it works fine at 2.1.3 version 👍 Thanks.
The only issue is slow response after clicking the Save button on the dialog.

**Comment by alexkvak** [comment]
> The only issue is slow response after clicking the Save button on the dialog.

this is because slack api client uses rate limit mechanism and in our case there are more than one request to it. 
So the second and all next requests are delayed
