### ISSUE TITLE
Unable to find channel with name

### ISSUE THREAD

**Issue by patricklabrie** [alexkvak/teamcity-slack#129]
I've read the other issues. I'm not too sure since it doesn't have very verbose information.
I enter Slack channel without the #, I've validated the bot oauth is good, restarted TC server last friday, still today it doesn't find it. The bot joined the channel I'm trying to find (though the bot joined after the restart). It isn't a new channel since the plugin install.
I'm on 2.1.0
Any clue to diagnose further ?
Also, I don't know where to find the Try it. I was assuming it would show up after the Save but I can't save due to the Slack channel unfound issue.
Thanks for the help, plugin look great.

**Comment by aeroradish** [comment]
I just had this problem -- I solved it by going to the new channel and clicking on the heading to bring up the settings. I then clicked the "Integrations" tab, and added this App to the channel. The channel then showed up on Team City.

**Comment by patricklabrie** [comment]
The bot was already added to the channel following these instructions.
I revalidated the oauth in TC, the bot config/access, that the bot was indeed in the channel. Nothing moved.

**Comment by alexkvak** [comment]
Could you try https://api.slack.com/methods/conversations.list/test ?
Provide your token and enter `public_channel,private_channel` into `types` field.

**Comment by patricklabrie** [comment]
it works, but we have so many channels, at the end I get
"response_metadata": {
        "next_cursor": "dGVhbTpDOVk1SjdRRVA="
    }
    
   Based on https://api.slack.com/docs/pagination
Is that potentially the issue ? The channel doesn't show up in the first page of data retrieval searching on the website.

**Comment by alexkvak** [comment]
Thanks for the issue! It should be fixed in v2.1.3

**Comment by patricklabrie** [comment]
Confirm it's been fixed!
