### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by billabrian6** [alexkvak/teamcity-slack#13]
I'm not sure if I'm misunderstanding the instructions, but I can't get this to work. When I click "Try" I get the message "Something went wrong".

I followed the instructions for Slack, making sure that I'm using the bot key, and the channel without the "#".

Is the public artifact URL necessary? I tried mydomain.com/system/artifacts but I get nothing. I'm using the newest version of TeamCity running on AWS.

**Comment by alexkvak** [comment]
You should you Try it feature only if you have at least one finished build. Do you have it?

**Comment by billabrian6** [comment]
Yes. I have at least 15 builds. Do you know if it's related to /system/artifacts being public? I would prefer that it not be public, but your plugin doesn't specify it as optional.

**Comment by alexkvak** [comment]
Artifacts url is optional.
Could you provide more details?
Please check your previous builds branch and branch mask in you slack notifications settings.

**Comment by alexkvak** [comment]
I've created #14, I'll fix it soon.

**Comment by billabrian6** [comment]
I appreciate it. I'm excited to use this plugin!

**Comment by alexkvak** [comment]
@billabrian6 please try with latest version

**Comment by billabrian6** [comment]
@alexkvak I got the latest version installed, thanks for updating. It says "Error: previous build not found"

[Error screenshot](https://puu.sh/yPu3D/89bc348cfc.png)

I do have builds though, you can see them in the screenshot.

[Screenshot of latest builds](https://puu.sh/yPu04/b7def5aaf7.png)

Do you have any other ideas?

This is the version of Team City that I'm using. TeamCity Professional 2017.2.1 (build 50732)

**Comment by alexkvak** [comment]
Please attach also your slack notification settings (popup)

**Comment by billabrian6** [comment]
@alexkvak Here are my [settings](https://puu.sh/yPExU/2a6f4ef620.png)

**Comment by alexkvak** [comment]
The problem is that you specify the exact branch name but TeamCity does not extract branch name into builds. 
In this case you can specify `.*` as branch mask and plugin should proceed all branches even when TeamCity does not know their names.

**Comment by billabrian6** [comment]
It works now, but the branch is "Unknown". Do you know if there is a setting I'm missing that will allow me to use an explicit branch?

**Comment by alexkvak** [comment]
I guess you need to do something like this
https://stackoverflow.com/questions/23415704/select-git-branch-for-teamcity-build

**Comment by billabrian6** [comment]
@alexkvak Thanks for your help!

**Comment by rsagar-commcise** [comment]
Hi alexkvak,

Thanks for the Pluggin its good one, i am able to get notification only for master branch, not for the other branches.........pleas can you help me to resolve it

**Comment by alexkvak** [comment]
Please provide your settings

**Comment by raullukacs** [comment]
Hi @alexkvak ,

I am having the same problem with the Unknown branch and I am unable to do it based on the link you provided. Is there anything else I can do ?

@billabrian6  how did you manage to get it working ?

I am using TeamCity Professional 2018.1.2 (build 58537)

Thanks,

**Comment by alexkvak** [comment]
@raullukacs do you see your vcs branch in TeamCity in builds list?
![default](https://user-images.githubusercontent.com/1052418/51614823-87971a80-1f37-11e9-8a2d-8c14fde1a6c5.png)
