### ISSUE TITLE
Icon and Display name not showing

### ISSUE THREAD

**Issue by AndyBarnettCTM** [alexkvak/teamcity-slack#15]
Any idea what I'm doing wrong? I followed your setup instructions and it's all working except the bot is posting with a username of 'TeamCity' and with an icon of the Slack 'bots' integration.

The screenshot below shows that the display name and icon I've set isn't being used, any idea what to do?

https://i.imgur.com/ppnxa0K.png

**Comment by alexkvak** [comment]
There is no ability to change default sender name, it is "TeamCity".
I added enhancement #16, track this issue please

**Comment by alexkvak** [comment]
@AndyBarnettCTM please try to change sender name

**Comment by AndyBarnettCTM** [comment]
Sender name can now be successfully set in TeamCity, thank you!
I'm still a bit confused though, I assumed the name and icon would have been grabbed from the Bots integration instead of having to manually set it as a field in Teamcity? When I view the bot user in slack, it has a username and avatar. Is it possible to just use these?

**Comment by alexkvak** [comment]
Is your app now show default slack avatar or avatar from your app settings?

**Comment by AndyBarnettCTM** [comment]
It's still the default icon for the Bots integration I'm afraid:
https://imgur.com/a/eNyeE

**Comment by alexkvak** [comment]
Hm, but it’s not slack message, it’s settings page on api.slack.com

**Comment by AndyBarnettCTM** [comment]
I must have misunderstood, it's not too much of a problem, thanks for implementing the textbox for the bot name!
