### ISSUE TITLE
Setup instructions are incomplete and the error message "Unable to create session by config" is unhelpful

### ISSUE THREAD

**Issue by mhalttu** [alexkvak/teamcity-slack#19]
I'm trying to setup the plugin and I believe I'm following the instructions correctly. When I press "Submit" the plugin is not enabled and it shows the following message: "Unable to create session by config"

What am I doing wrong?

**Comment by mhalttu** [comment]
The problem is that you need to create a Bot user for the Slack App. I think you should update the instructions to tell this much more clearly. Currently that step is completely omitted from the instructions. 

Also the error message should be much more descriptive.

**Comment by alexkvak** [comment]
Hi @mhalttu,
could you describe your setup process and make a PR?

> Also the error message should be much more descriptive.
I'll be appreciate if you offer another one message for your case in terms of Slack API.

**Comment by mhalttu** [comment]
I decided to use another plugin for the slack integration, so I am hesitant to spend more time on this. You can close this issue you wish. However, briefly:

Instead of:
>* Create new app.
>* Got to Features - Incoming Webhooks and Activate Incoming Webhooks
>* Now go to OAuth & Permissions and copy Bot User OAuth Access Token.

You should say something like
>* Create new app.
>* Got to Features - Incoming Webhooks and Activate Incoming Webhooks
>* Got to Bot Users - Add Bot Users and [extra details as needed]
>* Now go to OAuth & Permissions and copy Bot User OAuth Access Token.

The error message could e.g. say: "Unable to create session by config. For ideas how to fix this issue, please see https://github.com/alexkvak/teamcity-slack/issues/1"

**Comment by alexkvak** [comment]
Thanks for your feedback, I've improved these parts of code.
