### ISSUE TITLE
Error adding Slack to project

### ISSUE THREAD

**Issue by dythim** [alexkvak/teamcity-slack#2]
I'm having trouble adding a channel for the notifier.  I have the OAuth key entered for our site, and I've made a channel #build-status which the app bot has joined, but it does not seem to recognize the channel.  Not sure what to do -- any help?

![image](https://user-images.githubusercontent.com/543502/32903029-f4ebe7ee-cac1-11e7-961e-9ad3a752d782.png)

![image](https://user-images.githubusercontent.com/543502/32903136-3d03dd34-cac2-11e7-8c60-e225ee1c21d3.png)

**Comment by alexkvak** [comment]
You need to specify channel name without heading `#`
I make respective changes in readme

**Comment by dythim** [comment]
Thanks, that did help.
