### ISSUE TITLE
Plugin does not apply teamcity proxy settings

### ISSUE THREAD

**Issue by mvput** [alexkvak/teamcity-slack#20]
1. Created a new app on api.slack.com
2. Activated the feature incoming webhooks
3. Added a bot users 
4. Installed the app into the channel.
5. Copied the bot user oauth access token.

Result: `Unable to create session by config`

**Comment by alexkvak** [comment]
Please install v1.1.1 and you can see Slack API error code after this error message.
The list of this error code is [here](https://api.slack.com/methods/rtm.start#errors)

**Comment by mvput** [comment]
Now it returns the following error: `Unable to create session by config: Connect to slack.com:443 [slack.com/52.85.250.20] failed: Connection timed out: connect`.

**Comment by alexkvak** [comment]
So it's not a plugin problem :)

**Comment by mvput** [comment]
Allright, i'm checking the proxy settings.

**Comment by mvput** [comment]
I've configured the proxy on teamcity. But does the slack plugin works based on teamcity proxy or the agent proxy? The proxy works for teamcity because i can download and install updates from teamcity.

**Comment by alexkvak** [comment]
Plugin works only on teamcity, not agents.

**Comment by mvput** [comment]
Does the plugin pick up the proxy from teamcity?

**Comment by alexkvak** [comment]
No. What proxy settings do you mean?

**Comment by mvput** [comment]
You can configure a proxy for teamcity for outgoing connections. See: [Configure TeamCity to Use Proxy Server for Outgoing Connections](https://confluence.jetbrains.com/pages/viewpage.action?pageId=74845225#HowTo...-ConfigureTeamCitytoUseProxyServerforOutgoingConnections)

For e.q.
```
# For HTTP protocol
## The domain name or the IP address of the proxy host and the port:
teamcity.http.proxyHost=proxy.domain.com
teamcity.http.proxyPort=8080
 
## The hosts that should be accessed without going through the proxy, usually internal hosts. Provide a list of hosts, separated by the '|' character. The wildcard '*' can be used:
teamcity.http.nonProxyHosts=localhost|*.mydomain.com)

# For HTTPS protocol
## The domain name or the IP address of the proxy host and the port:
teamcity.https.proxyHost=proxy.domain.com
teamcity.https.proxyPort=8080
 
## The hosts that should be accessed without going through the proxy, usually internal hosts. Provide a list of hosts, separated by the '|' character. The wildcard '*' can be used:
teamcity.https.nonProxyHosts=localhost|*.mydomain.com
```

**Comment by alexkvak** [comment]
No plugin was developed for 2017.1.2
I'll check what I can do with this feature.

**Comment by alexkvak** [comment]
Now you can specify proxy settings with `-D` argument or in `internal.properties` file.

**Comment by NikolaR** [comment]
Seems to work. Slightly confusing:

1. No proxy settings, TeamCity fails to connect to public internet (e.g. to check for updates)
2. Slack plugin fails to connect
3. Set proxy
4. TeamCity starts to work
5. Slack plugin still does not work
6. Restart TeamCity service
7. Slack integration starts working

It would be helpful not to cache this information.

**Comment by alexkvak** [comment]
It depends on https://github.com/Itiviti/simple-slack-api which I cannot upgrade due to this issue https://github.com/Itiviti/simple-slack-api/issues/230
