### ISSUE TITLE
Master branches are always unknown

### ISSUE THREAD

**Issue by ErikJanssonWork** [alexkvak/teamcity-slack#21]
I have set up several projects now and they all have unknown master branches in this plugin. When I look in bitbucket I see that they in fact are named "master".

**Comment by alexkvak** [comment]
As you can see, in build history there is no _master_ branch name, isn't it? 
So TC does not parse the branch name and does not provide it to plugins.

You should configure branch specification as described [https://confluence.jetbrains.com/display/TCD10/Working+with+Feature+Branches#WorkingwithFeatureBranches-Logicalbranchname](here)
