### ISSUE TITLE
If "only trigger when build changes" checked, first build for branch ignored

### ISSUE THREAD

**Issue by MadloptD** [alexkvak/teamcity-slack#23]
Hi. If i check "only trigger when build changes" first status is ignored for success and failed build. 
For example, i have wildcard autobuild for any branch. When developer create new branch and build failed there is no notify.

**Comment by alexkvak** [comment]
Hi,
good point, we have the same problem, I guess :)

**Comment by MadloptD** [comment]
Thanks.
Can you help with {branch}. If i set Branch as .* the {branch} notify as "Unknown"

**Comment by alexkvak** [comment]
See #21

**Comment by MadloptD** [comment]
Ok. Sorry, but I still do not understand.
In VCS root "Default branch" has value "refs/heads/develop" and 
"Branch specification:" has value "+:refs/heads/*".
In History i see logical branch names (develop, navigation_control etc)
At "Slack" tab at "Branch:" i has value ".*".
What is wrong? 
Thanks for your help

**Comment by alexkvak** [comment]
I guess you should try
`+:refs/heads/(*)`

**Comment by alexkvak** [comment]
@MadloptD please install latest plugin version (see releases)
