### ISSUE TITLE
Don't skip unknown users, but also don't try to tag them

### ISSUE THREAD

**Issue by mbalmes** [alexkvak/teamcity-slack#26]
{mentions} doesn't show the users if their slack name is not the same name that teamcity reports. It would be helpful if we could still see the name, but not tag them.

**Comment by alexkvak** [comment]
But you can see users in changes list, mention is designed to mention slack users.

**Comment by mbalmes** [comment]
This may be too specific to our usage, but when we have a build fail it's very helpful to have the list of contributors visible in the slack message. We've been using a custom implementation for a while and just switched to this plugin and are missing this functionality. We've found that having the list of contributors shown in slack helps it get fixed faster, because users are less likely to do the multiple clicks to get to the changes list. I know the {changes}  placeholder will list the changes with the contributor's name, but that's pretty verbose for what we need. Maybe implementing another placeholder that will tag the slack user if possible, otherwise just listing the name would work. If you agree with the need I would gladly add it myself and submit a pull request.

**Comment by alexkvak** [comment]
Please try newest release

**Comment by mbalmes** [comment]
Awesome, thanks!
