### ISSUE TITLE
Plugin unable to rout to server

### ISSUE THREAD

**Issue by hiddenwolf1589** [alexkvak/teamcity-slack#28]
When attempting to setup the plugin any attempts by the modify the plugin's setting/access the Slack tab in the project tries to access the wrong IP address.  When trying to submit plugin settings I get redirected to the wrong IP (plugin attempts to connect to 10.1.2.55 when my IP is 10.1.2.134).

I was able to modify the form action (pictured below) using Chrome Dev Tools to correct the IP address and the form submitted correctly.
![image](https://user-images.githubusercontent.com/8403438/36690908-b69f69a8-1b01-11e8-8d31-af940a9fe870.png)

Looking at the network calls when selecting the Slack tab in a project and it appears that they are also using the same incorrect IP address.

I attempted to restart the TeamCity service in hopes that this was just an odd Java environment issue, but this did not help.

TeamCity version used: 2017.2.2

**Comment by alexkvak** [comment]
Please show your TeamCity server URL in global settings
