### ISSUE TITLE
Getting 403 Forbidden when configuring the plugin after installation

### ISSUE THREAD

**Issue by karthikeayan** [alexkvak/teamcity-slack#30]
1. Installed the plugin
2. Opened slack admin page
3. Entered OAuth token
4. Entered Sender Name
4. Click Submit

Getting this below error.

403 Forbidden: Responding with 403 status code due to failed CSRF check: request's "Origin" header value "null" does not match Host/X-Forwarded-Host header values or server's CORS-trusted hosts, consider adding "Origin: http://<my_teamcity_server>.ca.com" header.

**Comment by alexkvak** [comment]
Do you use any proxy? 
Please check your [TeamCity Server URL](https://confluence.jetbrains.com/display/TCD10/Configuring+Server+URL)

**Comment by alexkvak** [comment]
@karthikeayan any news?

**Comment by leandro-dlieve** [comment]
I have the same issue

**Comment by alexkvak** [comment]
So what is your details?
