### ISSUE TITLE
Attach artifacts

### ISSUE THREAD

**Issue by DPohorielov** [alexkvak/teamcity-slack#34]
Hi!
Thank you for this plugin. 
Is it possible to attach the artifacts from TeamCity? URL link is fine but we have a lot of users in build chat who doesn't have access to TeamCity.
Kindly Regards

**Comment by alexkvak** [comment]
Hi,
we had the same issue and it was solved with [artifact links](https://github.com/alexkvak/teamcity-slack#artifact-links) feature.

**Comment by alexkvak** [comment]
@DPohorielov is it suitable to your case?
