### ISSUE TITLE
Response for preflight is invalid (redirect)

### ISSUE THREAD

**Issue by heaven** [alexkvak/teamcity-slack#35]
Receiving this error when opening the tab:
<img width="1440" alt="screen shot 2018-06-14 at 20 33 35" src="https://user-images.githubusercontent.com/126732/41428532-088f3034-7013-11e8-8e05-abe77918b1b8.png">

TeamCity Professional 2017.2.2 (build 50909)
Slack Integration 1.1.7

**Comment by alexkvak** [comment]
Please show your location bar

**Comment by heaven** [comment]
Hi, here's the value:
http://teamcity.wegohealth.com/viewType.html?buildTypeId=Carmen_Default&tab=Slack&branch_Carmen=__all_branches__

**Comment by alexkvak** [comment]
Location is ok. Could you provide full redirect response?

**Comment by heaven** [comment]
It seems the cause was that it uses HTTPS while the page is loaded using HTTP.

**Comment by alexkvak** [comment]
So your TeamCity works via HTTP and via HTTPS at same time?

**Comment by alexkvak** [comment]
Please check the setting Server URL on Administration - Global Settings page

**Comment by heaven** [comment]
Yup. I think we did not configure the redirect to force SSL but this is not mandatory. Since we can load the page over HTTP the plugin has to use the same protocol (or use a protocol-relative URL //teamcity.wegohealth.com/...).

**Comment by heaven** [comment]
> Please check the setting Server URL on Administration - Global Settings page
Correct, we had https:// there. This fixed the problem but I am wondering why didn't this break other functionality.

**Comment by alexkvak** [comment]
It seems that plugin should construct relative path, and not it constructs full URL. 
There was an issue when TeamCity was served not in root but in "subfolder" e.g. http://my.com/teamcity/
I make some investigations and try to fix this. 
Thanks for report.
