### ISSUE TITLE
No preview available

### ISSUE THREAD

**Issue by sandweel** [alexkvak/teamcity-slack#36]
Hello.
All notification has no preview - **[no preview available]**. I using default text from your example.
Is it fixable by my side?

**Comment by alexkvak** [comment]
Hello, it's Slack application behaviour, while the message has no content, but only attachments.

**Comment by sandweel** [comment]
Yes I know but how I can move attachments to the message body or some text like a build status?

**Comment by alexkvak** [comment]
You cannot do this. 
It breaks the current view with vertical line, so I use attachments.

**Comment by sandweel** [comment]
I think if you'll add new block above the box **Message template** for text body it will be very helpful.
I don't needed to open slack application that I could read build status.

**Comment by sandweel** [comment]
@alexkvak Could you please tell will you do any updates for showing preview build?
Thank you in advance.

**Comment by alexkvak** [comment]
I've discussed it with my team mates and we don't see the right solution here.
I've wrote to Slack twitter and the answer was: we don't plan to provide any api to specify exlicitly the message preview.
So, I stay this issue open and wait for some other ideas.

**Comment by j-j-marvin** [comment]
I'd say that configuration whether to send message as attachment or plain text might solve the issue in some way. There will be at a least a choice between neat vertical view and preview of the message. @alexkvak does it make sense from your point of view?

**Comment by alexkvak** [comment]
This is interesting, we can use emoji ⛔️, ⚪️ and ✅ to indicate the build status.
But I doubt that backward compatibility e.g. switching between message representation is needed.
@adbrv what’s your thoughts?

**Comment by j-j-marvin** [comment]
By the way I've check the integration I have between WP and slack. It has both text (with emojis) and attachment with vertical. View. I believe that you can easily reach that if `message.message` is not empty here (SlackGatewayL130):

`Try(x.sendMessage(channel, message.message, message.attachment.orNull, channelChatConfiguration))`
