### ISSUE TITLE
why is branch a required field

### ISSUE THREAD

**Issue by redxeagle** [alexkvak/teamcity-slack#37]
Branch is a required field.  Why? 

We have TeamCity configurations without any repository behind. 
They are set up as nightly test runs based on some artifact dependencies from other builds.

**Comment by sandweel** [comment]
You can you `.*` for branch field. It means all existing branches.

**Comment by redxeagle** [comment]
Hm, tried this before. And then it does not work. Now it works fine. :-)
Perfect. The Issue can be closed. Was Layer 8 issue.

**Comment by alexkvak** [comment]
@sandweel thanks for the answer!
@redxeagle branch mask is expected to be a valid regular expression, so it's better when user explicitly specify it even `.*`
