### ISSUE TITLE
Timeout when submitting OAuth Access Token

### ISSUE THREAD

**Issue by ShervinVR** [alexkvak/teamcity-slack#38]
I've followed the steps to make a slack app, activated incoming webhooks etc...

When I go to enter  Bot User OAuth Access Token in the teamcity admin slack page, I click submit, but after about 15 seconds I get ERR_CONNECTION_TIMED_OUT page on chrome.

Have you run into this? Any guidance?

I'm using Teamcity 2017.1.3 along with v1.1.8 of your build

Thanks so much for your help.

**Comment by alexkvak** [comment]
Could you check your teamcity-server.log at Administration - Diagnostics page?

**Comment by ShervinVR** [comment]
Hi Alex,

Thanks for the quick response. I'm looking at the teamcity-server.log (and tried a couple time to submit the token again) but nothing seems to be getting logged.

**Comment by alexkvak** [comment]
Did you read #1 ?

**Comment by ShervinVR** [comment]
Thanks for the link. However, I can't even get an error "Unable to create session by config".

**Comment by alexkvak** [comment]
Ok, let's start from the core. 
Please try to fetch from your teamcity host the URL `https://slack.com/api/rtm.start?token=<your_auth_token>`

**Comment by alexkvak** [comment]
> What is the Public Artifacts URL?
let's discuss it later, it cannot be the reason of current behaviour.

**Comment by alexkvak** [comment]
@ShervinVR did you find the reason?

**Comment by ShervinVR** [comment]
Hi Alex!

Thanks for following up. I sort of left it for a while, until today I came across the general admin settings in teamcity, and noticed that the Server URL was incorrect! (doh!)

Thanks so much for your help :)
