### ISSUE TITLE
Personal build notifications aren't getting through

### ISSUE THREAD

**Issue by kbaley** [alexkvak/teamcity-slack#4]
I installed the plug-in and enabled personal notifications. I also set up the Slack notifier on my profile to send a notification on any build, default branch, whenever the build starts, just as a test. But I don't get any notifications on Slack. Just wondering if I'm missing something.

The Slack notifications for specific build configurations, as outlined in the documentation, work fine.

**Comment by alexkvak** [comment]
Only admins can setup notifications into Slack, that's why personal notifications are allowed only for failed builds.
This means that if build fails changes authors become personal notification.
I'll update readme.

**Comment by alexkvak** [comment]
Also I want to add personal notifications checkbox into build settings. I'll notify you in this issue.

**Comment by kbaley** [comment]
Thank you @alexkvak

**Comment by alexkvak** [comment]
Will be done soon #5
