### ISSUE TITLE
Would like to be able to use notification template syntax in notifications

### ISSUE THREAD

**Issue by philip-z** [alexkvak/teamcity-slack#42]
specifically I want  var.buildShortStatusDescription so the number of tests is highly visible

**Comment by alexkvak** [comment]
You can use teamcity variables for this purpose. In one of your build steps you can determine the tests number and set teamcity variable. 
Then plugin can read this variable and pass to the message.

https://github.com/alexkvak/teamcity-slack#parameters-placeholders
