### ISSUE TITLE
Teamcity artifacts url is invalid

### ISSUE THREAD

**Issue by yusano** [alexkvak/teamcity-slack#43]
Hi,

I'm trying to get the APK link to sent to Slack by using [https://github.com/alexkvak/teamcity-slack#artifactlinks](url)

But the URL format sent to Slack is invalid, it sent like this:

`http://<TeamCity_host_url>/repository/download/<BuildName>/<Environment>/<buildid>/my.apk`

but the correct link format should be like this:

`http://<TeamCity_host_url>/repository/download/<BuildName>_<Environment>/<buildid>:id/my.apk`

**Comment by alexkvak** [comment]
Hi,

is your nginx configured properly?

**Comment by yusano** [comment]
Hi,
yes, it is.
