### ISSUE TITLE
{users} field is not returned

### ISSUE THREAD

**Issue by ITASAPI** [alexkvak/teamcity-slack#45]
Maybe I do not understand the set up enough but when using the following template the {users} field is not populated when builds fail and the 'personal' slack notification is not sent.

<{link}|{name} - #{number}>
Status: *{status}*
{users}
{reason}

Notes:
- users are set up with the same email address in TeamCity as in Slack
- Administration > Slack > Personal notifications enabled (only if build fails) - is checked.

**Comment by alexkvak** [comment]
Hi, and what about vcs users? Are they associated in teamcity?
Please provide your build configuration slack settings.
