### ISSUE TITLE
Allow alerts for builds with no branch or vcs root

### ISSUE THREAD

**Issue by davidatthepark** [alexkvak/teamcity-slack#46]
First off, thank you for making this plugin. My team loves it.

I was wondering if it is possible to allow alerting for build tasks that do not have vcs roots configured. For example, one of our TeamCity build projects does not have a vcs root. It just performs one or more tasks.

Thanks!

**Comment by alexkvak** [comment]
VCS only used for branch mask matching, if there is no VCS, this matching is skipped.

Please try to specify .* as a branch mask.
 
It should work :)

**Comment by davidatthepark** [comment]
This worked! Awesome. Thank you so much!
