### ISSUE TITLE
Error: Previous build not found

### ISSUE THREAD

**Issue by lamak** [alexkvak/teamcity-slack#50]
Hi, we're using TeamCity Professional 2018.1.2 (build 58537)
Has two branches for build:
default branch name: refs/heads/master and refs/heads/dev with no branch specification filled
With branch in slack config: master, refs/heads/master, 
when I'm try — previous build not found, but there is a lot of them.
<img width="1596" alt="screen shot 2018-10-09 at 18 13 03" src="https://user-images.githubusercontent.com/795844/46655468-0c5f6200-cbef-11e8-9636-452b5e4ad18d.png">

**Comment by alexkvak** [comment]
Please attach screenshot with you slack notifications config

**Comment by lamak** [comment]
<img width="549" alt="screen shot 2018-10-09 at 19 14 49" src="https://user-images.githubusercontent.com/795844/46659111-a0cdc280-cbf7-11e8-9d0b-8abf18afcc28.png">

**Comment by alexkvak** [comment]
And you receive notifications with such config?

**Comment by lamak** [comment]
There hasn't any build after that, so can't say about real notification, but 'Try it' worked only once on same config, but branch .* — got a test message.

**Comment by alexkvak** [comment]
Your TeamCity does not see your branch name so I guess notifications will not be sent.

**Comment by lamak** [comment]
I think so, so is there any way to set the branch name to TeamCity?

**Comment by alexkvak** [comment]
Please see #21 and https://stackoverflow.com/questions/23415704/select-git-branch-for-teamcity-build
