### ISSUE TITLE
Personal notifications don't work

### ISSUE THREAD

**Issue by martynakaminska** [alexkvak/teamcity-slack#51]
Hello,

I just installed this plugin and it's functionality works ok for channels. However it is not sending any private notifications. Are there any prerequisites or additional configuration to set?

Cheers,
Martyna

**Comment by alexkvak** [comment]
Hi, 
please attach your slack settings for build configurations

**Comment by martynakaminska** [comment]
Project settings:
![image](https://user-images.githubusercontent.com/32266057/46734259-9c9eb500-cc8a-11e8-98b6-ff68c98a9aa0.png)

Global settings:
![image](https://user-images.githubusercontent.com/32266057/46734318-c35ceb80-cc8a-11e8-95b6-84e1cba69b3d.png)

**Comment by alexkvak** [comment]
Looks good. Are emails is VCS and in Slack the same?

**Comment by martynakaminska** [comment]
Yes
![image](https://user-images.githubusercontent.com/32266057/46735137-44b57d80-cc8d-11e8-9df5-415de48ae374.png)

**Comment by alexkvak** [comment]
This plugin does not support TeamCity notification system.

**Comment by martynakaminska** [comment]
In this case I don't understand your question from previous comment

**Comment by alexkvak** [comment]
Every user has email in VCS and in Slack. Plugin sends personal notification only if commiter email is registered for one of Slack users.

**Comment by martynakaminska** [comment]
Both have same email but in VCS is private

**Comment by alexkvak** [comment]
What do you mean as private?

**Comment by martynakaminska** [comment]
Like this
![image](https://user-images.githubusercontent.com/32266057/46740865-b3013c80-cc9b-11e8-83c1-55d4d62870d9.png)

**Comment by alexkvak** [comment]
Oh sorry, the main thing that your VCS email must be associated with TeamCity users.
So if you open build changes you must see user name not emails 
![default](https://user-images.githubusercontent.com/1052418/46742242-47c16580-ccaf-11e8-9d49-f15f2b33573b.png)

**Comment by martynakaminska** [comment]
We have if configured too:

![chrome_2018-10-10_15-18-59](https://user-images.githubusercontent.com/32266057/46742996-0e352e00-cca0-11e8-9f34-0a862c89ae20.png)

**Comment by alexkvak** [comment]
So your settings looks correct. 
Does your build status corresponding to the slack notification settings? 
It should be cancelled or failed and contain your changes.

**Comment by alexkvak** [comment]
There is no answer for a long time.
