### ISSUE TITLE
"Unable to create session by config: missing_scope" issue when attempting to enable plugin

### ISSUE THREAD

**Issue by adamkmccarthy** [alexkvak/teamcity-slack#52]
Hi @alexkvak 

I/ using Teamcity version `2018.1.3`, I installed the plugin as per the instructions in the README but for some reason I keep getting the error shown below upon checking the enabled box, saving credentials etc:

<img width="442" alt="screen shot 2018-10-15 at 15 55 58" src="https://user-images.githubusercontent.com/1059521/46958958-d6105f80-d092-11e8-9a52-e33561f85e63.png">

Is there a log in `Teamcity/logs` that might lend some additional information? I've tried all fields etc and nothing seems to get me to any other state. Thanks for your help!

**Comment by alexkvak** [comment]
Hi,
You need no additional information while this error message is direct from slack api https://api.slack.com/docs/oauth-scopes
Check once again your application permissions according to readme.

**Comment by adamkmccarthy** [comment]
Aha, my bad. Thanks for the help!
