### ISSUE TITLE
Memory leak detected by Eclipse Memory Analyzer

### ISSUE THREAD

**Issue by testworksau** [alexkvak/teamcity-slack#59]
Firstly, thanks for the plugin, it works well!

Our TeamCity server ran out of memory a couple of times in the past month or so. The last time this happened, we took a memory dump from the TeamCity administration interface to find out why. 

The results of the dump file analysis are shown in the image below - it looks like the web socket sessions from `simpleslackapi` are not getting cleaned up.

We are using version 1.1.8 of this plugin, with TeamCity 2018.1.3

![image](https://user-images.githubusercontent.com/11973031/53915339-d0ec9500-40b3-11e9-9a7d-a0e3f5b8114d.png)

This problem may be related to this issue, which was fixed in simple slack api release 1.2.0

https://github.com/Ullink/simple-slack-api/issues/180

**Comment by alexkvak** [comment]
@testworksau thank you too, good catch!
Would you like to make a PR? 🙂

**Comment by alexkvak** [comment]
@testworksau I've updated simple-slack-api up to 1.2.0, but now it hang while creating connection session. 
I cannot find respective issue in its repo, could you?

**Comment by testworksau** [comment]
@alexkvak sorry for the delay getting back to you. I found this: 

https://github.com/Ullink/simple-slack-api/issues/174

**Comment by alexkvak** [comment]
Itiviti/simple-slack-api was removed in 2.0.0
