### ISSUE TITLE
Setup in TeamCity 2017 fails

### ISSUE THREAD

**Issue by cpsaez-Lendsum** [alexkvak/teamcity-slack#6]
After setup the OAuth access token, click save and the next message appears:

"Unable to create session by config"

Team city version -> 

TeamCity 2017.1.5 (build 47175), effective release date 2017-Apr-10, currently running in the ...

**Comment by alexkvak** [comment]
Hi, did you read #1?

**Comment by alexkvak** [comment]
@cpsaez-Lendsum

**Comment by bweber** [comment]
@alexkvak I am running into the same issue and followed the instructions in issue #1

**Comment by alexkvak** [comment]
Could you provide more information about your current settings? Like in #2

**Comment by dev704** [comment]
@cpsaez-Lendsum Have you Activated Incoming Webhooks for the App you created in api.slack.com?

**Comment by alexkvak** [comment]
@bweber any details?
