### ISSUE TITLE
Unable to find channel with name "channel"

### ISSUE THREAD

**Issue by itdoginfo** [alexkvak/teamcity-slack#61]
I create new channel test-tm in slack. When adding this channel to the field "Slack channel", I get an error
```
Unable to find channel with name test-tm
```
![Screenshot from 2019-03-19 15-32-26](https://user-images.githubusercontent.com/11143109/54607006-52ea9f80-4a5e-11e9-85ad-dc44aa7eb6fb.png)

There is no such problem when adding "old" channels

**Comment by alexkvak** [comment]
@itdoginfo please wait a couple of minutes and retry

**Comment by itdoginfo** [comment]
> @itdoginfo please wait a couple of minutes and retry

Already passed more than an hour. Unfortunately, nothing has changed
I am using version 1.1.8

**Comment by itdoginfo** [comment]
After a day I was able to add a channel

**Comment by alexkvak** [comment]
Channel list update does not rely on plugin but on [slack api](https://github.com/Ullink/simple-slack-api) library it uses.
