### ISSUE TITLE
Plugin does not work with no VCS attached builds

### ISSUE THREAD

**Issue by revoldver** [alexkvak/teamcity-slack#65]
I try to use plugin with regular build contains only "SSH Exec" steps and doesn't have any VCS root attached. Plugin does not work in this configuration (tried to fill branch field with "master").
What the branch (or any) should I use in plugin configuration or how to emulate the branch to use plugin?

**Comment by alexkvak** [comment]
@revoldver pleasy try `.*`

**Comment by revoldver** [comment]
It works! Thank you very much!
