### ISSUE TITLE
Add support for "Triggered By"

### ISSUE THREAD

**Issue by NikolayMetchev** [alexkvak/teamcity-slack#69]
It would be good to be able to say who/why the build was triggered as part of the slack message.

**Comment by alexkvak** [comment]
@NikolayMetchev is it enough to add `{triggeredBy}` placeholder which is the same as `Triggered by:` on build overview page?

**Comment by NikolayMetchev** [comment]
@alexkvak Yes that would be great. Thanks.

**Comment by alexkvak** [comment]
@NikolayMetchev you can solve this issue by using `{%teamcity.build.triggeredBy%}` placeholder

**Comment by NikolayMetchev** [comment]
That works pretty good. It would be good to make it into links to actual users within slack similar to how `{mentions}` works.

**Comment by alexkvak** [comment]
But it this case those users will become useless Slack notifications, it's not pretty good.
What problem you try to solve?

**Comment by NikolayMetchev** [comment]
We do our deployments via Teamcity. Those deployments are done by someone manually triggering a build configuration which performs the actual deployments to production. I want our teams' slack channel to be published to anytime that deployment build configuration is triggered so that the team is aware a deployment is happening.

**Comment by alexkvak** [comment]
So you just need triggered by as information not for notification. You don't need to notify user who was triggered the build, isn't it?
You just need to get the notification in your `deploy` channel with the record who was triggered the build.

**Comment by NikolayMetchev** [comment]
Correct. However if the username is linked you get extra slack functionality that can be useful at times. You can more easily direct message that user for example. 
For the record I would like to say that `{%teamcity.build.triggeredBy%}` solves my requirements and the slack linking is a "nice to have" that is low priority.

**Comment by alexkvak** [comment]
So let's close this issue and return to it when it should be useful. :)
