### ISSUE TITLE
Does not work with the new TC 2019.1 design

### ISSUE THREAD

**Issue by dennisdoomen** [alexkvak/teamcity-slack#71]
In TeamCity 2019.1 the tabs have been replaced by a new design. In this (default) view, the app no longer works.

**Comment by alexkvak** [comment]
![изображение](https://user-images.githubusercontent.com/1052418/61282214-9ca48600-a7c3-11e9-88af-a66ed79c0b86.png)
are you sure?

**Comment by dennisdoomen** [comment]
You're right! 

Sorry about that.
