### ISSUE TITLE
Plugin fails after TeamCity 2019.1.3 upgrade.

### ISSUE THREAD

**Issue by AlkisFortuneFish** [alexkvak/teamcity-slack#73]
After upgrading to TeamCity 2019.1.3, the plugin has stopped working. The log contains the attached callstack.
[TC.log](https://github.com/alexkvak/teamcity-slack/files/3696969/TC.log)

**Comment by alexkvak** [comment]
What plugin version do you have?

**Comment by AlkisFortuneFish** [comment]
According to the version displayed on the Plugin List, 1.2.0.

**Comment by alexkvak** [comment]
It seems that your `slackIntegration.json` contains incorrect characters. 
Please see #17 while I upgrade my TC.

**Comment by AlkisFortuneFish** [comment]
Yep, that's right. The message templates contained emojis. Removing them from the json config fixes the issue but of course leaves us with the problem that otherwise perfectly valid templates containing Unicode do not work.

**Comment by alexkvak** [comment]
Is the emojis stored as bytes sequence (e.g. `\xF0\x9F\x98\x81`) or not?

**Comment by AlkisFortuneFish** [comment]
They are not. They are stored as unescaped UTF-8 in the json. They were inserted using the UI.

**Comment by alexkvak** [comment]
@AlkisFortuneFish please try release 1.3.0
Feel free to re-open if issue is still reproduces

**Comment by AlkisFortuneFish** [comment]
It works, thanks for the fix. One thing, the version didn't actually get bumped, 1.3.0 is still 1.2.0 in teamcity-plugin.xml.

**Comment by alexkvak** [comment]
@AlkisFortuneFish thanks! Release was re-published
