### ISSUE TITLE
Slack email warning TLS1.2

### ISSUE THREAD

**Issue by Lechus** [alexkvak/teamcity-slack#75]
> On 19 February 2020, Slack will end support for TLS (Transport Layer Security) versions 1.0 and 1.1. We’ve identified that one or more of your Slack apps are impacted by this change. If you don’t upgrade your app to TLS 1.2, requests sent to any Slack endpoint will fail. 

Teamcity 2019.13, Java8 on Win Server2012R2
Not sure if this needs to be fixed in the plugin or on the server level, but connection to Slack is not using TLS12.

Could you give your thoughts or give an option to force TLS12 when your plugin connects to Slack server?

Cheers

**Comment by alexkvak** [comment]
According to this [article](https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default) http client should use TLS 1.2 in Java 8.
