### ISSUE TITLE
No "Slack" tab on build configuration after installing plugin

### ISSUE THREAD

**Issue by eyeezzi** [alexkvak/teamcity-slack#77]
After installing the plugin and restarting the TeamCity server, I added the Slack OAuth token to TeamCity UI > Administration > Slack. However, I do not see any "Slack" tab (or navigation pane item) in any build configuration home.

Teamcity Version: 2019.1.3
Plugin Version: 1.3.0

**Comment by alexkvak** [comment]
Could you provide build configuration home screenshot?

**Comment by eyeezzi** [comment]
@alexkvak Screenshots below.

First I installed the plugin, restarted my server, and enabled the plugin.
![Screen Shot 2019-10-28 at 12 10 26 PM](https://user-images.githubusercontent.com/9389872/67710150-a3bf6080-f97c-11e9-96c9-2a7acb82417e.png)

Then I setup the plugin with a Slack OAuth token which I obtained following the instructions [here](https://github.com/alexkvak/teamcity-slack#install-plugin-)
![Screen Shot 2019-10-28 at 12 10 59 PM](https://user-images.githubusercontent.com/9389872/67710299-ee40dd00-f97c-11e9-8813-77cd0d4f005e.png)

According to the docs, I'm supposed to see [this "Slack" tab](https://github.com/alexkvak/teamcity-slack/blob/master/_doc/slack-tab.png) in my build configuration page. But its nowhere to be found.

![Screen Shot 2019-10-28 at 12 19 23 PM](https://user-images.githubusercontent.com/9389872/67710936-34e30700-f97e-11e9-849b-5624c865a644.png)

![Screen Shot 2019-10-28 at 12 05 24 PM](https://user-images.githubusercontent.com/9389872/67711010-56dc8980-f97e-11e9-9bf9-45ab4d1fc529.png)

**Comment by alexkvak** [comment]
Please take a look at the last screenshot. There is `Build Configuration Home` at the right upper corner.

What you see now is the build configuration settings page.

**Comment by eyeezzi** [comment]
@alexkvak I did not post the a screenshot of the Build Configuration Home because it contains too many sensitive data (names and stuff). But it still does not have the Slack tab. Have you tested this plugin on a modern version of TeamCity? Cause the screenshots in the doc appear ancient. If so, please post one with a slack tab somewhere that allows me configure the message stuff...I think TeamCity has changed how notifications work since your readme was updated.

**Comment by alextim-empawa** [comment]
@eyeezzi I guess you don't see it because of new UI that is switched on. It is really hard to find, please see attached screenshot:
![image](https://user-images.githubusercontent.com/56697699/68546629-2581a600-03e1-11ea-80ad-1566983c3bdf.png)

**Comment by eyeezzi** [comment]
@alextim-empawa Thank you! That is the new location indeed, it's really hard to find. It'd be great to update the docs to also show this new UI.

**Comment by alexkvak** [comment]
This is common issue with the new TeamCity UI. 
Feel free to make a PR to the plugin docs!
