### ISSUE TITLE
Unable to find channel with name X for private channel

### ISSUE THREAD

**Issue by ufna** [alexkvak/teamcity-slack#78]
Trying to setup notifications into private channel, but got "Unable to find channel with name X". App is added to this channel. What I should do to enable this feature?

**Comment by alexkvak** [comment]
So your bot can send messages to this channel via Slack API?

**Comment by ufna** [comment]
I think yes, but I've just followed the tutorial https://github.com/alexkvak/teamcity-slack#install-plugin-

**Comment by alexkvak** [comment]
While simple-slack-api reads groups list only on connect, you should re-connect to Slack.
The only one way to do it now — restart the whole TeamCity server.

**Comment by alexkvak** [comment]
Just created issue for this #79

**Comment by ufna** [comment]
Thanks, restart helped!
