### ISSUE TITLE
"Status: Failed" when the build was cancelled (stopped manually)

### ISSUE THREAD

**Issue by alextim-empawa** [alexkvak/teamcity-slack#80]
when the build is stopped manually expected status in slack notification "cancelled" but received "failed"

Slack plugin 1.3.0
TeamCity 2019.1.5 (build 66605)

**Comment by ofirnn** [comment]
We're facing the same issue

**Comment by shachar-ash** [comment]
We  are facing the same issue

**Comment by panasico** [comment]
We're facing the same issue

**Comment by alexkvak** [comment]
@panasico @shachar-ash @ofirnn @alextim-empawa  could you check in latest version?
