### ISSUE TITLE
"Branch: Unknown"

### ISSUE THREAD

**Issue by alextim-empawa** [alexkvak/teamcity-slack#81]
the branch parameter with filter .* in notification message replaced as "Unknown"

Slack plugin 1.3.0
TeamCity 2019.1.5 (build 66605)

**Comment by alexkvak** [comment]
@alextim-empawa could you first read already existing issues?

https://github.com/alexkvak/teamcity-slack/issues?utf8=%E2%9C%93&q=is%3Aissue+unknown

**Comment by alextim-empawa** [comment]
sorry, my fault didn't check existing issues.
