### ISSUE TITLE
provide enable/disable toggle to each item

### ISSUE THREAD

**Issue by YoungjaeKim** [alexkvak/teamcity-slack#92]
Hi. many thanks for your effort. 

It would be good to support Enable/Disable checkbox toggle for each slack item of a build. Without it, all configured items including channel, branch, and message contents should be removed when I tentatively test a build.

**Comment by alexkvak** [comment]
Hi Kim,

You can change message template and remove all useless information

**Comment by YoungjaeKim** [comment]
@alexkvak Hi. thanks for the reply. what I meant is to enable/disable one by one. Would it be nice? :)
![image](https://user-images.githubusercontent.com/1265284/72347823-52717280-371c-11ea-870d-ceffd3974aaf.png)

**Comment by alexkvak** [comment]
Hm, interesting. 

What use-case do you have?

**Comment by YoungjaeKim** [comment]
@alexkvak for me, there was a period to mute the notification. but I didn't want to remove the template messages. 
🤔 Wait a minute.. what if I uncheck all trigger options? will it send in all successs/fail conditions or mute at all??

**Comment by alexkvak** [comment]
> will it send in all successs/fail conditions

I guess not

**Comment by YoungjaeKim** [comment]
Let me close it. It seems to make _disable_ a notification when we uncheck all trigger conditions.
