### ISSUE TITLE
Adding a negative lookbehind regex makes interface disappear

### ISSUE THREAD

**Issue by ricjspa** [alexkvak/teamcity-slack#98]
**Steps to reproduce**

1. Enable plugin
2. Navigate to 'Settings' for a build
3. Add a slack notification rule
4. Set the regex to: `.*(?<!--private)$`
5. Interface dissapears

This is almost certainly due to the '<!--' part of the regex not being escaped for HTML output.

**Comment by alexkvak** [comment]
@ricjspa Thanks for the report!
