### ISSUE TITLE
TeamCity build parameters (system or otherwise) arent being translated

### ISSUE THREAD

**Issue by JustinGol** [alexkvak/teamcity-slack#99]
I built a new notification thats meant to read TeamCity parameters but this isnt working for me. Im using TC 2018.2.1. I tried both system and configuration parameters and tried different variations of:
- {%system.xyz%}
- {%xyz%}

I looked into the code below and cant see a reason why it doesnt convert the parameter to its real value, assuming the build object works as expected. 

[MessageBuilder line to read parameters](https://github.com/alexkvak/teamcity-slack/blob/af520013b3b2ea0ec1109ea97f44e688b48db769/slackIntegration-server/src/main/scala/com/fpd/teamcity/slack/MessageBuilder.scala#L81)

**Comment by alexkvak** [comment]
Hi, 

Does your parameter presents at build Parameters tab?

<img width="704" src="https://user-images.githubusercontent.com/1052418/75006849-4481e080-5484-11ea-99b0-dd6de369db50.png">

**Comment by JustinGol** [comment]
Hi Alex, it does, see below. It was called slack-notification-target-database which I created for testing purposes but I also had a system parameter that I tried too unsuccessfully.

This was my message format: <{link}|{name}> {%slack-notification-target-database%} Status: {status}

![image](https://user-images.githubusercontent.com/42610502/75006978-c7785a80-54c7-11ea-8b1d-71bb9b7c1f5e.png)

**Comment by alexkvak** [comment]
I guess the reason of this behavior is that your parameter name contains dashes and this symbol is absent in the regex on https://github.com/alexkvak/teamcity-slack/blob/af520013b3b2ea0ec1109ea97f44e688b48db769/slackIntegration-server/src/main/scala/com/fpd/teamcity/slack/MessageBuilder.scala#L68 

I'll fix it in couple of days.

**Comment by JustinGol** [comment]
> I guess the reason of this behavior is that your parameter name contains dashes and this symbol is absent in the regex on
> 
> https://github.com/alexkvak/teamcity-slack/blob/af520013b3b2ea0ec1109ea97f44e688b48db769/slackIntegration-server/src/main/scala/com/fpd/teamcity/slack/MessageBuilder.scala#L68
> 
> I'll fix it in couple of days.

I tested the regex but was only testing against the % and didnt add a hyphen. I see now it doesnt work. Appreciate it Alex.

**Comment by alexkvak** [comment]
By the way I did so while teamcity always separates words in parameters with dots :) 

But it does not matter, it's still bug.

**Comment by JustinGol** [comment]
Thats a good point, I never noticed that before. We always had a convention to use hyphen. On their docs they recommend the following: [a-zA-Z0-9._-*]

[TeamCity Parameter Name Restrictions](https://www.jetbrains.com/help/teamcity/configuring-build-parameters.html#ConfiguringBuildParameters-Parameternamerestrictions)

**Comment by JustinGol** [comment]
Thanks for fixing this and for doing it so quickly
